### ISSUE TITLE
Checkbox of host setting in ssh development do not display correctly

### ISSUE THREAD

**Issue by jxzhn** [mani-sh-reddy/mariana-light#1]
I'm using ssh remote development, and i find that all checkbox of host setting items don't display correctly when using mariana-light theme. They are ok when using other themes.

Mariana-light:
<img width="982" alt="image" src="https://github.com/user-attachments/assets/e1704451-268f-4e2e-9e6e-ff1330923997">

Other theme:
<img width="982" alt="image" src="https://github.com/user-attachments/assets/ecde2633-4a8d-4d96-afc7-e842650b2350">

**Comment by mani-sh-reddy** [comment]
Are you able to install the plugin on the host? 
![Screenshot 2024-07-18 at 13 33 18](https://github.com/user-attachments/assets/44d84813-ba83-4fb6-8039-80f35d396f53)

**Comment by jxzhn** [comment]
> Are you able to install the plugin on the host? ![Screenshot 2024-07-18 at 13 33 18](https://private-user-images.githubusercontent.com/47571755/349955878-44d84813-ba83-4fb6-8039-80f35d396f53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MTg4MjUsIm5iZiI6MTcyMTYxODUyNSwicGF0aCI6Ii80NzU3MTc1NS8zNDk5NTU4NzgtNDRkODQ4MTMtYmE4My00ZmI2LTgwMzktODBmMzVkMzk2ZjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDAzMjIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjOWZjNjVhODMyZDVjNzg4NzVhZDJlZTEyY2MxMGNkYjI3MjQxNDRiYTM0NjE4NWQ5MzAwZTQ2Y2ExYmM1NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XjxneaeBR3KXIPUD1juRdZJG66ktlmuQl2b-89Slzp8)

that does fix my problem, thanks
